version: '3'
services:

  db:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - "./.env" # required for POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD

  backend:
    build:
      dockerfile: Dockerfile
      target: devel
      context: .
    ports:
    - "8000:8000"
    volumes:
     - "./src:/devel"
    env_file:
      - ".env"
    depends_on:
      - db

volumes:
  postgres_data:
