# Generated by Django 4.2.6 on 2023-10-29 20:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_product_active_product_latitude_product_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("OPP", "OnPlacePayment"),
                            ("CARD", "Card"),
                            ("PAYPAL", "PayPal"),
                            ("BANK", "BankTransfer"),
                        ],
                        default="OPP",
                        max_length=6,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_rents",
                        to="api.product",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rents",
                        to="api.profile",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rent_status",
                        to="api.rentstatus",
                    ),
                ),
            ],
        ),
    ]
