# Generated by Django 4.2.6 on 2023-10-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rentstatus_rent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=8,
            ),
        ),
        migrations.DeleteModel(
            name="RentStatus",
        ),
    ]
