# Generated by Django 4.2.6 on 2023-10-29 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_rent_status_delete_rentstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
