# Generated by Django 4.2.6 on 2023-11-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rent_created_at_rent_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name_plural": "Product categories"},
        ),
        migrations.AlterModelOptions(
            name="productreviews",
            options={"verbose_name_plural": "Product reviews"},
        ),
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
