# Generated by Django 4.2.7 on 2023-11-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviews',
            old_name='owner',
            new_name='created_by',
        ),
    ]
