name: Heroku deploy

on:
  workflow_run:
    workflows: ["Run tests"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Deploy django to heroku
      uses: nyakaz73/heroku-django-deploy@v0.81
      with:
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email_address: ${{ secrets.HEROKU_API_EMAIL }}
        use_git: true
        git_branch: main
        disable_collect_static: true
