name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  execute_tests:
    name: Install requirements and execute tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute tests
        env:
          DJANGO_DEBUG: TRUE
          DJANGO_SETTINGS_MODULE: loopable.settings
          DJANGO_ENV: LOCAL
        run: python src/manage.py test -v 2
